use_frameworks!

platform :ios, "9.3"


target 'MSXLFormValidationPopup_Example' do
  pod 'MSXLFormValidationPopup', :path => '../'

  target 'MSXLFormValidationPopup_Tests' do
    inherit! :search_paths

    
  end
end
